### ISSUE TITLE
Travis-Connection seems broken

### ISSUE THREAD

**Issue by kronn** [svenfuchs/safemode#28]
It seems like no new builds are being triggered from github on travis.

https://travis-ci.org/svenfuchs/safemode/requests does not list any requests...

@svenfuchs could you look into this?

**Comment by svenfuchs** [comment]
for some reason the webhook was not active (as in `[ ] active`), i've fixed that, created a new branch from master, and that just started a build https://travis-ci.org/svenfuchs/safemode/builds/367685548

so i assume this is fixed

**Comment by kronn** [comment]
Thank you, works again. I hope the next build turns out green, but that is a different issue. :-)
